apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: prod
type: Opaque
data:
  username: YXBwdXNlcg==       # base64 of 'appuser'
  password: YXBwcGFzc3dvcmQ=   # base64 of 'apppassword'